#!/bin/bash
00 02 * * 1-5 /etc/cron.daily/removeSASLogFiles.sh > /dev/null %
00 06,13 * * 1-5 /etc/cron.daily/checkServerStatus.sh > /dev/null %
# 40 11 07 * * /etc/cron.weekly/pgbackup_audit_archive.sh > /dev/null %
00 02 * * 1-5 [[ -e /mnt/FTP_BS/SYS-MULE-UcrBeslut ]] && echo 'Disken är monterad. Puh!' || (echo "Subject: $(hostname) - Montering försvunnen"; echo; echo "Disken under /mnt/FTP_BS tycks inte längre vara monterad. Åtgärda genom att logga in som root och skriva: mount /mnt/FTP_BS") | sendmail -i fredrik.hansson@regionuppsala.se  > /dev/null 2>&1